sudo: required

language: bash

services:
  - docker

before_install:
  - docker build -t chefserver .
  - docker run --privileged -t --name chefserver -d -p 443:443 kodelint/chefserver
  - docker ps -a


